### ISSUE TITLE
Does v13.0.0 of this package support Angular 14?

### ISSUE THREAD

**Issue by cristobaldominguez95** [angular-extensions/elements#125]
In our company we have an Angular library which is currently in Angular 13 and depends on this package. We would like to update our library to angular 14 but we are not sure if the current version of this package supports Angular 14 or not.

Could someone please confirm if it works with Angular 14, and if not, when is it planned to add support for it?

Any response would be highly appreciated. Thank you.

**Comment by tomastrajan** [comment]
Yes was released 👍
