### ISSUE TITLE
Add FAQ section detailing error which happens when installing latest @angular-extensions/elements in Angular 7

### ISSUE THREAD

**Issue by tomastrajan** [angular-extensions/elements#13]
As the title says, following will lead to an error...

Its something about the internal `defineInjectable`...

Would be great to add FAQ section which would explain how to fix that error ( by installing @angular-extensions/elements@^7.0.0 )

**Comment by MrWhiteNerdy** [comment]
Does this issue still need work? It looks like the answer is found at https://github.com/angular-extensions/elements#supported-angular-versions to match the major versions.

**Comment by tomastrajan** [comment]
@MrWhiteNerdy you are right, good to close! Thank you for your contribution!
