### ISSUE TITLE
Angular 15 migrations - inject()

### ISSUE THREAD

**Issue by tomastrajan** [angular-extensions/elements#139]
Migrate all `constructor()` code to `inject()` and remove ` "useDefineForClassFields": false,` flag from every `tsconfig.json` file.

**Comment by 9kubczas4** [comment]
I'll start working on it.

**Comment by 9kubczas4** [comment]
Hi @tomastrajan,

I've raised PR with adjustments: https://github.com/angular-extensions/elements/pull/143.

/Pawel

**Comment by tomastrajan** [comment]
@9kubczas4 thanks again!
