### ISSUE TITLE
Playing with the examples makes the website routing messed up

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular-extensions/elements#14]
I ran some examples and went to other pages, and saw that it messes up the routing of the docs.

<img width="1440" alt="Screen Shot 2019-09-05 at 11 06 13 AM" src="https://user-images.githubusercontent.com/2327532/64359287-a5e4ee80-cfcd-11e9-850c-d5a00c84b993.png">
<img width="1437" alt="Screen Shot 2019-09-05 at 11 06 39 AM" src="https://user-images.githubusercontent.com/2327532/64359288-a5e4ee80-cfcd-11e9-9486-bee509c6355e.png">

**Comment by tomastrajan** [comment]
@mohammedzamakhan experienced that too before, didn't have time to investigate yet, any ideas why this might be the case ?

**Comment by mohammedzamakhan** [comment]
@tomastrajan it feels to me that the web components created by stencils are the issue here. Both ionic and decko-qrcode are created using stencil, and only interacting with those component is causing this issue.

I remember that even on Stencil docs, they had routing issues long back when I was reading their docs 🤷‍♂

**Comment by tomastrajan** [comment]
@mohammedzamakhan removed stencil examples, used wiredjs and ink instead
