### ISSUE TITLE
How to communicate the element ?

### ISSUE THREAD

**Issue by yarabsyp** [angular-extensions/elements#145]
Hello Team,

Is there any way to communicate the elements to component and vice versa.

Passing input to the element and element can dispatch the message. Kind of Event listener ? 
 
is there any way to communicate the data to element and element can pass back/emit some message ? 

Please advise

**Comment by raulmelo** [comment]
Hey @yarabsyp, you can use events  Output() and Input() vice versa.

mode simples 
[Video share data between](https://www.youtube.com/watch?v=PlvTveHGe8M)
