### ISSUE TITLE
Loaded Elements Replace All Content

### ISSUE THREAD

**Issue by adickson311** [angular-extensions/elements#16]
Angular v 8.6.0
@angular-extensions/elements v 8.6.0

I noticed this when registering the element alongside other html content in the App Component. The entire content is replaced by the loaded element, not just the dom element with the *axLazyElement directive.

I moved the *axLazyElement into a feature module/component, and still noticed that the entire app content was replaced with the loaded element.

I should note that I'm using the module configuration method, instead of the directive Input.

**Comment by adickson311** [comment]
This was due to my Element module still bootstraping against <app-root>, not this library.

**Comment by tomastrajan** [comment]
@adickson311 happy that you figured it out!
