### ISSUE TITLE
Make sure that .forRoot was called only once

### ISSUE THREAD

**Issue by tomastrajan** [angular-extensions/elements#20]
Would be nice to add guard that will make sure that the `forRoot` was called only once and provide nice error message if that is not the case...

One of the approaches is described in this article by @timdeschryver  https://dev.to/angular/guarding-your-angular-modules-lio

**Comment by vivekmore** [comment]
I'd like to submit a PR for this.
Is that fine?

**Comment by tomastrajan** [comment]
Hi @vivekmore ~

Thanks for the interest but there seem to be PR already open for this ... https://github.com/angular-extensions/elements/pull/21

Just missing some tests but I guess that will be added soon :)

**Comment by vivekmore** [comment]
I saw that after I put a comment. 😄

**Comment by tomastrajan** [comment]
Fixed in #21
