### ISSUE TITLE
ax-lazy-element *axLazyElementDynamic in *ngFor

### ISSUE THREAD

**Issue by janstadt** [angular-extensions/elements#25]
We have a use case similar to the one outlined here: https://github.com/angular-extensions/elements/issues/5

We have a container that knows which features the logged in user has and will send back an array of modules said user has access to. We then loop over these items and render them on the page. 

There seems to be a race condition or zone issue (??) with the dynamic directive when trying to render out multiple web components on to the page. What seems to happen is that it'll render out only the last web component multiple times. The source looks suspect as well:
![image](https://user-images.githubusercontent.com/1872087/66226993-c32adc80-e6a1-11e9-8f87-c73e158124e0.png)

Here is a stackblitz that demonstrates the issue: https://stackblitz.com/edit/axlazy-in-ngfor

FYI, stackblitz seems to hotload components and the CustomElementRegistry will not get wiped out on update so if you edit any of the code it'll complain. Workaround is to just refresh the entire page circa 2003.

You can also modify the existing view to have some type of event handler outside of the `ngFor` that will render out the second element but it seems that if these elements are rendered in an `ngFor` they are not rendering appropriately.

**Comment by tomastrajan** [comment]
Hi @janstadt !

Yes, this is a known issue, I have to update the docs, the thing is, a placeholder custom element  currently has to be unique so something like `<ax-lazy-placeholder-1>` (2, 3, 4 ...) Which doesn't really match that well with `ngFor` as I am not aware of making the tag name dynamic without stuff like `innerHTML` or similar DOM level approaches...

**Comment by janstadt** [comment]
I'll see if i can come up with something. One thing that i tested locally so far that works is to defer the ` host.name = this.tag;` from line 46 down into the `loadElement` promise (line 65 or something). Not sure if that'll jack things up or not and i feel like there must be a cleaner approach. 

What it comes down to is that the `TemplateRef` seems to be the same for each item inside the loop and it'll just replace whichever one is last. Im gonna research a bit more on how regular structural directives handle this type of dom manipulation. 

https://github.com/angular-extensions/elements/pull/26

**Comment by tomastrajan** [comment]
@janstadt I think I got it, fix coming soon :D Together with the a demo :)
