### ISSUE TITLE
axLazyElement works poorly with OnPush components

### ISSUE THREAD

**Issue by MagicCurlyHair** [angular-extensions/elements#33]
Currently, the directive works poorly with OnPush components, since change detection isn't triggered on an element's load. I believe the fix is as simple as calling ChangeDetectorRef.markForCheck() after the element has been loaded and inserted back into the component's view.

**Comment by tomastrajan** [comment]
@MagicCurlyHair definitelly something which could be added as it only happens rarely so should not have performance impact :) Mind creating a PR ?

**Comment by MagicCurlyHair** [comment]
@tomastrajan 

Sure, I'll do it
