### ISSUE TITLE
Property does not exist on type 'HTMLElement'.

### ISSUE THREAD

**Issue by kmanev073** [angular-extensions/elements#34]
Hi guys!

I've been trying to load 2 of my angular elements using the library. You can find them [here](https://github.com/kmanev073/EdoInput) and [here](https://github.com/kmanev073/EdoButton)

Here is the repo for the main app: [click](https://github.com/kmanev073/WebApp)

I have a 3rd project setup like this:
```
const options: LazyElementModuleOptions = {
  elementConfigs: [
    { tag: 'edo-button', url: 'https://kmanev073.github.io/EdoButton/dist/main-es2015.js' },
    { tag: 'edo-input', url: 'https://kmanev073.github.io/EdoInput/dist/main-es2015.js' }
  ]
};
```

Then I use my components as:
```
<edo-button *axLazyElement
></edo-button>

<edo-input *axLazyElement
></edo-input>

<edo-button *axLazyElement
></edo-button>
```

It all works and you just need to add some extra scripts to your index.html: 
```
<script src="https://kmanev073.github.io/EdoButton/dist/polyfills-es2015.js"></script>
<script src="https://kmanev073.github.io/EdoButton/dist/scripts.js" defer></script>
<script src="https://kmanev073.github.io/EdoButton/dist/polyfill-webcomp.js" defer></script>
```

Now the problem...
The EdoButton and the EdoInput both have Inputs and Outputs. When I try to use them like this:
```

<edo-button *axLazyElement
  [edoValue]="'-'"
  (edoClick)="onMinusClick($event)"
></edo-button>

<edo-input *axLazyElement
  [edoValue]="value"
  (edoChange)="onInputChange($event)"
></edo-input>

<edo-button *axLazyElement
  [edoValue]="'+'"
  (edoClick)="onPlusClick($event)"
></edo-button>
```

I get an error saying: 

```
ERROR in src/app/app.component.html(2,3): Property 'edoValue' does not exist on type 'HTMLElement'.
src/app/app.component.html(7,3): Property 'edoValue' does not exist on type 'HTMLElement'.
src/app/app.component.html(12,3): Property 'edoValue' does not exist on type 'HTMLElement'.

```

Any ideas on how to enable inputs and outputs?

**Comment by MagicCurlyHair** [comment]
Hi @kmanev073 

As far as I remember you need to add special [schema](https://angular.io/api/core/CUSTOM_ELEMENTS_SCHEMA) to the root module in your project.

The code will look like this:
```ts
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@NgModule({
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
  // more code here
})
```
This schema will tell Angular that you are using custom elements with custom inputs/outputs using native DOM API.

**Comment by kmanev073** [comment]
@MagicCurlyHair I've added the schema and it still doesn't work. I tried disabling ivy, still doesn't work. I've added a link to the main app repo so you can check it out.

**Comment by tomastrajan** [comment]
@kmanev073 With IVY this was sometimes happening even in pure Angular apps when there was some inheritance with components extending some base class which had (or didn't have `@Component` decorator. Didn't encounter such problems, also do you use `ngx-build-plus` to produce single bundle of your elements with everything included ??

**Comment by kmanev073** [comment]
@tomastrajan I tried disabling IVY and it still doesn't work... And yeah, I do use `ngx-build-plus` but does this affect the build process?. I've posted the repo of the consuming app you can try building it and see if it will work.

**Comment by tomastrajan** [comment]
@kmanev073 when I tried to use it with IVY it was working, did some 9.next.15 or so version which has much more fixes and IVY related features to 8.x maybe that could be the way? The 9 is currently in RC and will be out soon :)

**Comment by kmanev073** [comment]
@tomastrajan Well alright, I will just wait for 9. The issue can be closed.

**Comment by tomastrajan** [comment]
@kmanev073 please try it already with 9.rc.X just to be sure its that :)
