### ISSUE TITLE
Lazy loading Angular libraries

### ISSUE THREAD

**Issue by BossOz** [angular-extensions/elements#41]
Hello guys! 
I'm really new in Angular world so sorry about my questions!

I have some Angular libraries (developed by my colleagues) that are not on npm and I would like to load components that are exported by these.
My libraries are stored in a local folder and I'm trying to lazy load these libraries without success.

```
<ng-template #loading>Loading...</ng-template>
<ng-template #error>Error loading component</ng-template>
<mycomponent *axLazyElement="this.elementUrl; loadingTemplate:loading; errorTemplate:error; module: true"></mycomponent >
```
where 
`elementUrl = "./libraries/mylibrary.js";`

So I bring your "basic usage" example that uses `mwc-icon.js` and I saved the module url locally
`https://unpkg.com/@material/mwc-icon@0.6.0/mwc-icon.js?module`

Using the remote URL all is working as described.
Switching to the local path (`./libraries/mwc-icon.js`) I must change the internal import of the js but everything worked properly!

Now my question is? Is it possible to lazy load my libraries with your @angular-extensions/elements or I need to do some "transformation" to my libraries/components?

Thank you very much!

**Comment by tomastrajan** [comment]
Hi @BossOz !

If I understand correctly you mean "standard" Angular libraries and not bundles of Angular elements or other web components. In that case (depending on the content of the library) the approach will be a bit different.

I actually wrote an [article](https://medium.com/@tomastrajan/why-and-how-to-lazy-load-angular-libraries-a3bf1489fe24) about this topic a while ago, maybe this can help!

**Comment by BossOz** [comment]
Thank you @tomastrajan for the fast reply!
I have already read this article, thank you. 
So maybe is better to transform my standard Angular libraries to Angular components?
Thank you!

**Comment by tomastrajan** [comment]
@BossOz it depends what you want to acheive

Normal libs can be consumed as described in the article and it is simpler and leads to smaller total Javascript bundle size

Angular Elements are the components ( from libs ) that are built in isolation and made available as web components on some URL (where the bundle.js is deployed) this means there will be more Javascript but the lib will be independent so you for example dont have to rebuild every consumer SPA when there is a new version of the lib as described in the [use cases](https://angular-extensions.github.io/elements/#/docs/use-cases)

Cheers!

**Comment by BossOz** [comment]
Exactly what we want to reach: consume all the elements and upgrade them without to rebuild the SPA every time.
So your use case is perfect for us!
Thank you very much for your time!
