### ISSUE TITLE
Event binding not working

### ISSUE THREAD

**Issue by BossOz** [angular-extensions/elements#44]
Hello @tomastrajan,

I'm trying to have the Angular component instance using bindings with an `ax-lazy-element`.
Here a test project [https://github.com/BossOz/test-aee-bindings](https://github.com/BossOz/test-aee-bindings)

In my angular element `DesktopSystemEmptyElementComponent` I emit the event `componentReady` that, unfortunately, is not fired.

here the code of the html

```
<ax-lazy-element *axLazyElementDynamic="'vdr-empty-component', url: url; module: true"
                 (componentReady)="onComponentReady($event)">
</ax-lazy-element>
```

Why this event is not fired?
Is because that the emit is in the `ngOnInit()`?

Thank you!

**Comment by tomastrajan** [comment]
@BossOz could you also provide link to the implementation of the component ?

**Comment by BossOz** [comment]
I have added the implementation in the same repository.
Let me know if you need other!

**Comment by tomastrajan** [comment]
@BossOz one thing I can see is that the element itself does NOT need the `LazyElementsModule` or library at all, event looks good so its strange, please add also a button which emits other event to test it and also I would try to use it with `*axLazyElement` and hardcoded tag so we have a full picture of what is going on :)

**Comment by BossOz** [comment]
Thank you so much dude!
I will wait for your reply!

**Comment by BossOz** [comment]
Update: the event is fired using a button.

**Comment by tomastrajan** [comment]
@BossOz  looks like a timing issue ? Wat about using set timout in ng onInit ? or use ngAfter iweInit ??

**Comment by BossOz** [comment]
Yess! The event was fixed with the `setTimeout()` but now I have something strange on `$event` object.
Doing a `console.log()` inside my component, the result is was I was expecting.
Doing a `console.log()` in the fired event the same object is under `detail`.

Check the picture.
![consolelog](https://user-images.githubusercontent.com/4025510/75031276-2af19080-54a6-11ea-9508-22a337cbefab.png)


Is this correct?

**Comment by tomastrajan** [comment]
Hi @BossOz  !

The `details` I think come from the standard web `CustomEvent`, you can do `$event.details` in your template binding ;)
