### ISSUE TITLE
errors on angular-extensions.github.io/elements

### ISSUE THREAD

**Issue by lucky777** [angular-extensions/elements#45]
There is an error 404 with service worker. Navigation is impossible.

**Comment by tomastrajan** [comment]
Hi @lucky777 !

The `*axLazyELements` makes a request to load element bundle from an URL, that way the SW has to handle that address correctly as it intercepts the request, hope that helps!

**Comment by lucky777** [comment]
@tomastrajan please, take a look at https://angular-extensions.github.io/elements/
There is an error with SW and entire site doesn't works
![angular-extensions github io](https://user-images.githubusercontent.com/5920342/75671672-7151a700-5c7f-11ea-9d6d-86bb2c7640e5.PNG)

**Comment by lucky777** [comment]
Now it works
