### ISSUE TITLE
elements angular-extensions-elements.js Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by rogeraustinsam** [angular-extensions/elements#55]
Getting this error while using external url to load js file “angular-extensions-elements.js:184 Cross-Origin Read Blocking (CORB) blocked cross-origin response“

**Comment by tomastrajan** [comment]
Hi @rogeraustinsam!

This has probably more to do with your setup of the consumer application and server which serves the element.

The server needs to set correct content type and CORS headers.
The application has to be able to accept such request response.

**Comment by rogeraustinsam** [comment]
I Agree @tomastrajan
