### ISSUE TITLE
Getting "net::ERR_ABORTED 404 (Not Found)" while dynamically loading web component

### ISSUE THREAD

**Issue by yogibimbi** [angular-extensions/elements#60]
I have compiled a couple of Angular web elements and am trying to load them dynamically via the ax-lazy-element component like so:
`<ax-lazy-element *axLazyElementDynamic="tag, url: url; module: true; errorTemplate: error"
     [(node)]="node">`
`</ax-lazy-element>`
`<ng-template #error>Loading of {{url}} failed...</ng-template>`

In the component, I have
`public url = 'projects/elements/dist/components/type/item.js';`
`public tag = 'oyl-type-item'`

Just before the error message I am getting a warning
`sockjs.js:2999 WebSocket connection to 'ws://localhost:8100/sockjs-node/983/5jt2rk1u/websocket' failed: WebSocket is closed before the connection is established`
followed by the error
`angular-extensions-elements.js:210 GET http://localhost:8100/projects/elements/dist/components/type/item.js net::ERR_ABORTED 404 (Not Found)`

I can do an import with the very same path, aka
`const module = await import('projects/elements/dist/components/type/item.js');` and all is good.
Does the localhost:8100 that is apparently added by the ax-lazy-element component change things here?

However, when I pass the very same URL as a variable to import() as in
`path = 'projects/elements/dist/components/type/item.js';`
`import(path)`,
I get the error
`Warnings while compiling
...
Critical dependency: the request of a dependency is an expression`
Which is why I looked for an alternative in the first place and gave your library a spin. I'm just mentioning it because maybe those things are connected?

**Comment by tomastrajan** [comment]
Hi @yogibimbi !

Can you access this url `http://localhost:8100/projects/elements/dist/components/type/item.js` in your browser, is it really served by the dev ( or other server) ? It should display the file content.

**Comment by yogibimbi** [comment]
Hi Tomas,

in the browser, all those URLs are caught by the Angular router, so what i am getting in the browser when using http://localhost:8100/projects/elements/dist/components/type/item.js is "ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'projects/elements/dist/components/type/item.js' Error: Cannot match any routes." But that should not interfere with the calls made from within the app, right? I can still dynamically import libraries from within the app, as long as it gets the URL as a static URL instead of as a value from inside a variable, as described in the end of my ticket. My example in the ticket is not 100% homogeneous, though, it compares a promise with async/await, which in terms of the es version I am running, can make a difference (when using esnext as target and module setting in tsconfig.json, I am getting "WARNING: Zone.js does not support native async/await in ES2017"), but even when I run

import('../elements/type/item').then(({ItemComponent})=>{...})

const path = '../elements/type/item';
import(path).then(({ItemComponent})=>{...})

in a very stripped down application, the first import is fine while the second gets the error "ERROR Error: Uncaught (in promise): Error: Cannot find module '../elements/type/item'
Error: Cannot find module '../elements/type/item'". This is totally without your library, though, but it might hold some clues to what is going on in the background. I haven't gone much through the source code of your lib yet, so I am not aware of the mechanism you guys are implementing.

Cheers, Jörg

**Comment by tomastrajan** [comment]
@yogibimbi so then we confirmed the problem. With elements you have to serve standalone element bundle on some url to be bale to lazy load it using the library. 

(Its not ment to consume single files but pre built web components, eg Angualr element, native webcomponent, Stencil.js built webcomponents, ...)

To make this work with the Angualr CLI (webpack-dev-server)You have to make sure that you serve the element bundle on some URL and then you could use webpack [proxy](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md) to redirect calls to that url where the element bundle is served.

**Comment by yogibimbi** [comment]
ok, cool. That will be a bit difficult in an Ionic app, though...

**Comment by tomastrajan** [comment]
@yogibimbi then maybe comes the question why would you want to consume it as web components ? Usualy the reason is that you can independently release some widget which will be updated in consumer app because it is only referenced by the url. So that the consumer app does not need to be released and still gets the new widget.

**Comment by yogibimbi** [comment]
hehe, that is due to my expandable and top-secret hybrid mobile app :-D well, but, really, I am developing an app and want the UI components to be customizeable depending on the freely selectable datatype of the model, and eventually without having to recompile the entire app, so in the form of plugins.

**Comment by tomastrajan** [comment]
@yogibimbi then it sounds liek a good match, you just have to build and deploy your widgets somehow to some URL and serve them from there and then reference them by ursl in your consumer SPA, good luck ! Also you might want to look into ETAGs when serving element bundles (so that the url is alwys same but they are cached until the bundle content changes )

**Comment by yogibimbi** [comment]
The bundle thing would only be very much further down the line, at this stage of development I just want to have the structure in place to expand locally. Makes also sense because there is a loose coupling between the datatypes and the components, so I don't want the situation where I have a datatype that requires a remote component, because that can get changed or deleted and thus seriously affect the viewing of the model.
In the meantime I have a workaround that allows me to pseudo-dynamically (aka the URLs are not freely selectable because of this import problem, but the components get imported at run-time, so, once the problem with the import and URLs is hopefully solved, I can plug it right in; but currently I keep running into brick walls and it is not a priority for the MVP, so I can work on other things) import components, -angular components as well, as opposed to angular components compiled into elements- and is all in one place within the app, so expanding it would not require me to change the app all over, which is good enough for now.

**Comment by tomastrajan** [comment]
@yogibimbi sounds good! happy that you found an approach that works for you right now ;) And hopefully the lib can help you later down the road!
