### ISSUE TITLE
Cache problems

### ISSUE THREAD

**Issue by omanzelli** [angular-extensions/elements#65]
I have a shell application that loads all the Angular Elements using your library.
On my last update, I figured out cache problems, so the version of the elements was the previous.
In order to solve the problem I had to empty the browser cache.

I know that the cache is managed using the ETag of the file so how can check what's happening?

**Comment by tomastrajan** [comment]
@omanzelli you should see it in the dev tools ( network tab ) based on http status code and headers what exactly happened in your case

**Comment by felipeplets** [comment]
@omanzelli this is a general caching issue and not related to this library. I recommend a post on StackOverflow for a broader audience able to support you. 

@tomastrajan I believe we can close this issue as it's not related to the library behavior.

**Comment by tomastrajan** [comment]
@felipeplets i believe so too, thx for your support, appreciated!
