### ISSUE TITLE
A platform with a different configuration has been created. Please destroy it first.

### ISSUE THREAD

**Issue by gs-smuthyam** [angular-extensions/elements#68]
My use case is below

There are multiple angular elements being served from different hosts.
Another app(main) which consumes these elements.
All of them are using same version of libs.
I used externals in all the paces including main app so that the additional scripts file and polyfills would be served from main.
From the elements just included the main bundle file. 
It all works fine until I use second element from second bundle. 
Once I load the second bundle it errors out with the title and would not load it. Stack trace is as below. Any help to resolve this issue would be appreciated.

![image](https://user-images.githubusercontent.com/17039646/96029145-dd33f900-0e77-11eb-91be-e5e3cf49026c.png)

Not sure if this is something to do with **ngx-build-plus**

my externals config is as below 

module.exports = {
    output: {
      jsonpFunction: 'wpJsonpTimeline**<appName>**'
    },
    "externals": {
        "rxjs": "rxjs",
        "@angular/core": "ng.core",
        "@angular/common": "ng.common",
        "@angular/common/http": "ng.common.http",
        "@angular/platform-browser": "ng.platformBrowser",
        "@angular/platform-browser-dynamic": "ng.platformBrowserDynamic",
        "@angular/compiler": "ng.compiler",
        "@angular/elements": "ng.elements",
        "@angular/router": "ng.router",
        "@angular/forms": "ng.forms"
    }
}

**Comment by tomastrajan** [comment]
Hi @gs-smuthyam !

Interesting! Nice to see that you try to make this work with externals to reduce final bundle size! One thign we should try to rule out in the beginning is that if this also happens if you just use native `<script>` tags when loading elements (eg at the end of index.html, or even added later imperatively ) to figure out if this has to do more with the build process of your shell / elements or this library.

**Comment by gs-smuthyam** [comment]
Hi @tomastrajan ,

Thank you for taking your time. I have tried keeping at the end and removing preload too :). Unfortunately these did not work.

However, it worked with this change in angular json, sharing here for community.

output: {
     jsonpFunction: 'wpJsonp**<appName>**'
}

where the appName is unique key per element, may be one can use app name there.

**Comment by tomastrajan** [comment]
@gs-smuthyam thanks for sharing!
