### ISSUE TITLE
Is there a way to access the child component (angular element as web component)?

### ISSUE THREAD

**Issue by gs-smuthyam** [angular-extensions/elements#69]
Hi There, 

My use case is as below. 

User will drop the component on UI.
We then load angular element as web component at run time via axLazyElementDynamic directive. 
We will then initialise the component through typescript in the parent app. 
we used a wrapper class in the parent app to load the  actual web component considering we need the reference to be able to access public properties.
Though we use the wrapper, the reference is limited to the wrapper but not to the actual component loaded dynamically. 
Any insights on how we would be able to access public properties of the dynamically loaded web element using below? 

<ax-lazy-element *axLazyElementDynamic="'**comp-selector**', url: url;">
</ax-lazy-element>

where the **comp-selector** is the actual component

**Comment by tomastrajan** [comment]
Hi @gs-smuthyam !

I would recommend to use standard Angular `@Input()` and `@Output()` bindings 

`<ax-lazy-element *axLazyElementDynamic="'comp-selector', url: url;" [someInput]="data", (someOutput)="handler($event)">`

to pass in and receive any kind of data :)

**Comment by gs-smuthyam** [comment]
Hi @tomastrajan ,

Thank you for taking time. We have used the `@Input` decorator for making public methods available on the native element reference.

an example for reference is 
The angular element
```
@Input()
  saySomething() {
     console.log('Hello');
  }
```

this can be accessed in the page where the element is consumed as web component as below 

`this.ngEleRef.nativeElement.saySomething()`
