### ISSUE TITLE
Suggestions for local development. 

### ISSUE THREAD

**Issue by ZacharyRizer** [angular-extensions/elements#73]
First off, thank you for this package. It has made working with Elements so much more enjoyable. I'm trying to find a way to work locally without having to build every time. I'm currently setup to create Elements as sub-app's or widgets within a larger Angular project. I was following some of the examples on the ngx-build-plus repo where there are build scripts that concatenate all the js of the element, then copy it into the larger application's assets directory. Then I setup the LazyModuleConfigs to point the tag to the corresponding location in the assets folder. This works perfectly. I can work on a change in the Element, then build, then run the main app on Localhost and see if the change functions as it should. However I can't figure out how to have the element running on say localhost:4201, and the main app on 4200, and have the main app point to the localhost:4201 url for the element. This live-reload option would make development of the Element much more fluid. On the corresponding blog post there was a proxy config mentioned, but I can't seem to get that to work either. Any help would be appreciated.

**Comment by tomastrajan** [comment]
Hi @ZacharyRizer !

You have to use Angular CLI proxy options


Something like this...

```
{
    "dev": {
        "targets": [
            {
                "context": ["/how/element/is/referenced/in/consumer/"],
                "target": "http://localhost:4201/",
                "pathRewrite": {
                    "/how/element/is/referenced/in/consumer/main.js": "main.js"
                }
            }
        ]
    }
}
```
