### ISSUE TITLE
Preload using Service

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular-extensions/elements#8]
Once we have the `ElementConfig`'s support added, we need to support preloading all web components, even before they are shown in the browser using service

**Comment by tomastrajan** [comment]
This could be like preload all, or just the list of tags to preload

**Comment by mohammedzamakhan** [comment]
Yeah, that's the intent 😉

**Comment by tomastrajan** [comment]
@mohammedzamakhan this  could be the next one :)

**Comment by mohammedzamakhan** [comment]
oh I actually had reloading's PR almost ready. Will start work on this 🕺

**Comment by tomastrajan** [comment]
@mohammedzamakhan yeah can be in any order, but would prefer to keep them as separate PRs so are easier to understand / review, thank you very much!

**Comment by tomastrajan** [comment]
Fixed #22
