### ISSUE TITLE
Error Hook with details

### ISSUE THREAD

**Issue by pschalk** [angular-extensions/elements#81]
Hi,

is there a possibility to get more details about the error which occurred while loading the script?
Especially the HTTP Status Code + message would be interesting. 
(In our case we want to decide between missing js and auth problems)

In the code it looks like that there is just a hook if we could successfully load the script file.

Cheers,
Patrick

**Comment by arturovt** [comment]
Closing the issue since it's been implement in https://github.com/angular-extensions/elements/pull/96. You can now swallow script loading errors through `ErrorHandler.handleError`.
