### ISSUE TITLE
[FEATURE]: add abilty to reload all/explicit lazy laoded files

### ISSUE THREAD

**Issue by billyjov** [angular-extensions/elements#91]
Hi 

i have angular elements with own ngrx states.

if the parent app use logout, the lazy laoded files doest not clean their own states. 
I cannot clear just `onDestroy` in own apps because this would reload data each time the user change the route but always logged In.

Ist there a way to archieve this?

**Comment by tomastrajan** [comment]
@billyjov can you provide bit more details because I am not sure if I understand...

Custom elements as it seems can NOT be understand as of now so once the custom element (web component / Angular element) was loaded and registered it can't be removed without refreshing the whole page... 

https://stackoverflow.com/questions/53757396/unregister-custom-element

**Comment by arturovt** [comment]
@tomastrajan he probably means to re-bootstrap the `AppModule` since it's bootstrapped once. Well, if I do understand that correctly that would be a developer's responsibility to do that.

**Comment by tomastrajan** [comment]
@arturovt makes sense, can you please confirm @billyjov ?

**Comment by billyjov** [comment]
@arturovt @tomastrajan  The use case is as follow

- Subs apps (aka Ng Elements) have their own States (in this case NgRx). I use the state to store custom user settings like filter criteria 
- The Parent app manage the Authentication 
- If already loaded the lazy chunks for elements will be reused correctly 👍 
- Navigate to another page  keep the state for angular elements unchanged. The state can actually reset only if the user reload the page. So far not a problem because resetting state while using app is not needed actually
-  My issue is currently if a user logout and login with another credentials, then we have the old state for angular elements becauses the page was refreshed (the chunk was not probably reloaded)

Which solution to go ?

- I wanted to know if it's make sense to reload the chunk for lazy elements ?
- @arturovt How would you solve it with manually bootstrapping ?

**Comment by tomastrajan** [comment]
@billyjov this sounds more like clearing ngrx state on login / logout as the store is global so it should not be aware of elements, or do you have multiple stores?

I would expect that elements only register their state slices into your global store, right ?

If that's the case then you could use something like https://medium.com/@moneychaudhary/how-to-reset-the-state-or-clear-the-store-on-logout-in-ngrx-store-d2bd6304f8f3

**Comment by billyjov** [comment]
No elements keep their own states independently and cannot be access from outside by the global state.

So just dispatch an action on logout will not clear the ng elements states

The main reason of this is that our elements are full standalone apps. So ngrx will reinitialize (with the target state) each time we access the page where the custom element where loaded.

Removing the state  ondestroy  of the app component from the elements is not possible because otherwise you will have to reload the data each time you leave the page and then come back.

**Comment by arturovt** [comment]
> How would you solve it with manually bootstrapping ?

I've only assumed, since I said "if I do understand that correctly" :smile: 

That would be really helpful to have a minimal reproducible example, so we could've looked into that and try different solutions.

I don't think it's possible "physically" to reload chunks, since the already bootstrapped `AppModule` will be kept in memory with lots of other stuff (even if we remove the `<script>` element).

**Comment by billyjov** [comment]
Thanks @arturovt ..let me give a try .

**Comment by billyjov** [comment]
I get following errors after subscribe to message: 

First: 

```
ERROR DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "tag-name" has already been used with this registry
    at CustomElementRegistry.target.<computed> [as define]
```

Second: 


```

Unhandled Promise rejection: Failed to execute 'define' on 'CustomElementRegistry': the name "tag-name" has already been used with this registry ; Zone: <root> ; Task: Promise.then ; Value: DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "npp-invoicing-frontend" has already been used with this registry
    at CustomElementRegistry.target.<computed> [as define]

```


An the app not works anymore until browser refresh.

**Comment by arturovt** [comment]
@billyjov thanks, we gotta check if element exists in the registry. I’ll make a PR.

**Comment by arturovt** [comment]
Well, that’s an issue actually, you may see that it’s not possible to reload the chunk, since the element is already registered…

**Comment by billyjov** [comment]
@arturovt  Exactly.. That's what i'm looking for.

**Comment by tomastrajan** [comment]
@arturovt @billyjov which bring us to initial answer, currently unfortunately not possible...

```
Custom elements as it seems can NOT be unregistered as of now so once the custom element (web component / Angular element) was loaded and registered it can't be removed without refreshing the whole page...

https://stackoverflow.com/questions/53757396/unregister-custom-element
```

**Comment by arturovt** [comment]
Yeah, and I do think that not an issue of this library, but a restriction of implementation in the browser engine itself.

**Comment by tomastrajan** [comment]
> Yeah, and I do think that not an issue of this library, but a restriction of implementation in the browser engine itself.
> 
> I'd say you need to post some message through `window.postMessage` (e.g. logout) and clean the state in other apps.

**Comment by billyjov** [comment]
Yeah. Let's see what can be done in this area in the future.. Thanks guys for taking time to investigate this
